config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match '/about', to: 'home#about', via: 'get'
  match '/contacts', to: 'home#contacts', via: 'get'

  devise_for :users
  resources :users, only: [ :index, :show ]

  resources :articles, :pages
  resources :comments, only: [ :create, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  resources :dislikes, only: [ :create, :destroy ]

  resources :categories, only: [ :show, :create, :update, :destroy ]

  match '/admin/categories', to: 'categories#index', via: 'get'

  match '/:page', to: 'pages#show_by_name', via: 'get'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :category
  has_many :categories
  has_many :articles

  validates :name, presence: true, length: { in: 3..20 }
  validates :description, length: { maximum: 75 }

  def Category.tree
    Category.find_by_category_id 0
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate_user!, only: [ :index, :create, :update, :destroy ]
  before_action :admin_user!, only: [ :index, :create, :update, :destroy ]

  def index
    @tree = Category.tree
  end

  def show
    @category = Category.find(params[:id])
  end

  def create
    category = Category.create(category_params)
    if category.save
      flash[:green] = t('categories.created')
    else
      flash[:red] = t('categories.not_created')
    end
    redirect_to :back
  end

  def update
    category = Category.find(params[:id])
    if category.update_attributes category_params
      flash[:green] = t('categories.updated')
    else
      flash[:red] = t('categories.not_updated')
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:green] = t('categories.destroyed')
    redirect_to :back
  end

  private

    def category_params
      params.require(:category).permit(:name, :description, :category_id, :enabled)
    end

    def admin_user!
      unless current_user.admin?
        flash[:red] = t('categories.not_admin')
        redirect_to :back
      end
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
%li.collection-item
  = link_to category.name, category_path(category), class: 'tooltipped', 'data-tooltip' => category.description, 'data-position' => 'right'
  = link_to t('shared.delete'), category, method: 'delete', data: { confirm: t('shared.confirm') }, class: 'btn red right'
  %ul.collection= render category.categories unless category.categories.empty?

app/views/categories/index.html.haml
- provide :title, t('words.categories')
.container
  .row
    %ul.collection.col.s12
      %li.collection-header
        %h4= t 'words.categories'
      - Category.where(category_id: 0).to_a.each do |category|
        = render 'categories/category', category: category

app/views/categories/show.html.haml
- provide :title, @category.name
.container
  .row
    .col.s12
      %h1= @category.name
      .row
        = render @category.articles