config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match '/about', to: 'home#about', via: 'get'
  match '/contacts', to: 'home#contacts', via: 'get'

  devise_for :users
  resources :users, only: [ :index, :show ]

  resources :articles, :pages
  resources :comments, only: [ :create, :destroy ]
  resources :likes, only: [ :create, :destroy ]
  resources :dislikes, only: [ :create, :destroy ]

  resources :categories, only: [ :show, :create, :update, :destroy ]

  match '/admin/categories', to: 'categories#index', via: 'get'

  match '/:page', to: 'pages#show_by_name', via: 'get'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy
  has_many :dislikes, as: :dislikable, dependent: :destroy

  validates :title, presence: true, length: { in: 5..20 }
  validates :description, presence: true, length: { maximum: 75 }


end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :category
  has_many :categories
  has_many :articles

  validates :name, presence: true, length: { in: 3..20 }
  validates :description, length: { maximum: 75 }

  def Category.tree
    Category.find_by_category_id 0
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :likes, as: :likable, dependent: :destroy
  has_many :dislikes, as: :dislikable, dependent: :destroy

  validates :content, presence: true, length: { maximum: 140 }
end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :user
  belongs_to :dislikable, polymorphic: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true, uniqueness: { case_sensetive: false }
  validates :description, presence: true, length: { in: 5..140 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :articles
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def article_owner?(article)
    articles.include? article
  end

  def like(type, id)
    self.likes.find_by(likable_id: id, likable_type: type)
  end

  def has_like?(type, id)
    like(type, id).present?
  end

  def dislike(type, id)
    self.dislikes.find_by(dislikable_id: id, dislikable_type: type)
  end

  def has_dislike?(type, id)
    dislike(type, id).present?
  end

  def image_path(size = 200)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest email.downcase}?s=#{size}"
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :article_owner!, only: [ :edit, :update, :destroy ]

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.create(article_params)
    if @article.save
      flash[:green] = t('articles.saved')
      redirect_to @article
    else
      flash[:red] = t('articles.not_saved')
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update_attributes article_params
      flash[:green] = t('articles.updated')
      redirect_to @article
    else
      flash[:red] = t('articles.not_updates')
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:green] = t('articles.destroyed')
    redirect_to articles_path
  end

  private

    def article_params
      params.require(:article).permit(:title, :description, :body, :category_id)
    end

    def article_owner!
      @article = current_user.articles.find(params[:id])
      if @article.nil?
        flash[:red] = t('articles.no_owner')
        redirect :back
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!

  def create
    @comment = current_user.comments.create(comment_params)
    if @comment.save
      flash[:green] = t('comments.create')
      redirect_to @comment.commentable
    else
      flash[:red] = t('comments.not_create')
      redirect_to :back
    end
  end

  def destroy
    Comment.find(params[:id]).destroy!
    flash[:green] = t('comments.destroyed')
    redirect_to :back
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :commentable_type, :commentable_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contacts
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def create
    @like = current_user.likes.create(like_params)
    respond_to do |format|
      if @like.save
        format.js {}
        format.json { render json: @like, status: :create, location: @like }
      else
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    like = current_user.likes.find(params[:id])
    if like.present?
      id, type = like.likable.id, like.likable.class
      like.destroy
      @like = Like.new
      @like.likable_id = id
      @like.likable_type = type
      respond_to do |format|
        format.js {}
      end
    end
  end

  private

    def like_params
      params.require(:like).permit(:likable_id, :likable_type)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :new, :create, :edit, :update, :destroy ]
  before_action :admin_user!, only: [ :index, :new, :create, :edit, :update, :destroy ]

  def index
    @pages = Page.paginate(page: params[:page])
  end

  def show
    @page = Page.find(params[:id])
  end

  def show_by_name
    @page = Page.find_by_title(params[:page]) or not_found
    render 'show' if @page.present?
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.create(page_params)
    if @page.save
      flash[:green] = t('pages.create')
      redirect_to @page
    else
      flash[:red] = t('pages.not_create')
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes page_params
      flash[:green] = t('pages.updated')
      redirect_to @page
    else
      flash[:red] = t('pages.not_updated')
      render 'edit'
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    flash[:green] = t('pages.destroyed')
    redirect_to :back
  end

  private

    def page_params
      params.require(:page).permit :title, :description, :body, :meta_title, :meta_keywords, :meta_description, :enabled, :commentabled
    end

    def admin_user!
      unless current_user.admin?
        flash[:red] = t('pages.not_admin')
        redirect_to :back
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    base_title = 'VooVe'
    return base_title if title.nil?
    return "#{base_title} | #{title}" if title.present?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_errors.html.haml
- if object.errors.any?
  #errors
    %h6= t('errors.form_errors', count: object.errors.size)
    %ul
      - object.errors.full_messages.each do |e|
        %li= e

app/views/layouts/_flash.html.haml
.container
  .row
    .col.s12
      - flash.each do |key, value|
        .card-panel{ class: key }= value

app/views/layouts/_footer.html.haml
%footer.page-footer
  .container
    .row
      .col.l6.s12
        %h5.white-text= t('shared.site_name')
        %p.white-text ...
      .col.l4.offset-l2.s12
        %h5.white-text= t('words.links')
        %ul
          %li= link_to t('words.users'), users_path, class: 'white-text'
          %li= link_to t('words.articles'), articles_path, class: 'white-text'
          %li= link_to t('words.categories'), admin_categories_path, class: 'white-text' if user_signed_in? && current_user.admin?
          %li= link_to t('words.pages'), pages_path, class: 'white-text' if user_signed_in? && current_user.admin?
  .footer-copyright
    .container
      &copy; 2015 VooVe Ltd.
      = link_to 'More links', root_path, class: 'grey-text text-lighten-4 right'

app/views/layouts/_header.html.haml
.navbar-fixed
  %nav
    .container.nav-wrapper
      = link_to t('shared.site_name'), root_path, class: 'brand-logo'
      = link_to '<i class="mi">menu</i>'.html_safe, '#!', data: { activates: 'slide_out' }, class: 'button-collapse'
      %ul.right.hide-on-med-and-down= render 'layouts/nav'
      %ul#slide_out.side-nav= render 'layouts/nav'
      %ul#user_menu.dropdown-content
        - if user_signed_in?
          %li= link_to current_user.login, current_user
          %li= link_to t('session.sign_out'), destroy_user_session_path, method: 'delete'
        -else
          %li= link_to t('session.sign_in'), new_user_session_path
          %li= link_to t('session.sign_up'), new_user_registration_path

app/views/layouts/_nav.html.haml
%li= link_to t('words.main'), root_path
%li= link_to t('words.articles'), articles_path
%li= link_to t('shared.about_me'), about_path
%li= link_to t('words.contacts'), contacts_path
%li= render 'layouts/user_menu'

app/views/layouts/_user_menu.html.haml
%li
  %a.dropdown-button{ 'data-activates' => 'user_menu', href: '#!' }
    = user_signed_in? ? current_user.login : t('session.sign_in')
    %i.right.mdi-navigation-arrow-drop-down

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{ charset: 'utf8' }
    %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1.0' }
    %title= full_title(yield(:title))
    = csrf_meta_tags
  %body
    %header= render 'layouts/header'
    %main
      = render 'layouts/flash' unless flash.empty?
      = yield
    = render 'layouts/footer'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => false

app/views/shared/_likes_btn.html.haml
-# TODO: refactor it
- count, result = (item.likes.size - item.dislikes.size), 'exposure'
  - if count < 0
    - result += "_neg_#{-count}"
  - else if count == 0
    - result += '_zero'
  - else
    - result += "_plus_#{count}"
.likes-box.small{ id: "#{item.class}_#{item.id}" }
  = render 'likes/like_btn', item: item
  %i.mi= result
  = render 'dislikes/dislike_btn', item: item